### ISSUE TITLE
Retry block example in README is incorrect

### ISSUE THREAD

**Issue by justinlittman** [lostisland/faraday-retry#11]
In particular, it references `retries_remaining` instead of `retry_count` in https://github.com/lostisland/faraday-retry#call-a-block-on-every-retry

Should be:
```
response_statuses = []
retry_options = {
  retry_block: -> (env:, options:, retry_count:, exception:, will_retry_in:) { response_statuses << env.status }
}
```

**Comment by olleolleolle** [comment]
@justinlittman Cool! Would you like to make a PR?
