### ISSUE TITLE
Latest version available on rubygems.org is 2.0.0

### ISSUE THREAD

**Issue by kinkou** [lostisland/faraday-retry#24]
Hi, could you please update rubygems with the versions after 2.0.0?
Thank you in advance!

**Comment by iMacTia** [comment]
Hey @kinkou, thanks to you I identified an issue with our publish action that meant v2.1.0 was not correctly released.
I've now fixed that and recreated the release, so you should now be able to [see it in Rubygems](https://rubygems.org/gems/faraday-retry) 🙌 

v2.1.1 was not actually a version, but an attempt to fix the incorrect release of 2.1.0, so let's pretend that never existed 👀 

cc @olleolleolle

**Comment by kinkou** [comment]
Thank you very much!
