### ISSUE TITLE
Logging guidance

### ISSUE THREAD

**Issue by kwent** [lostisland/faraday-retry#29]
Hi,

Would love to have some guidance to how display logs when retries happen ( in how many seconds etc. )

Regards.

**Comment by iMacTia** [comment]
Hi @kwent, I believe you can use [the `retry_block`](https://github.com/lostisland/faraday-retry/tree/main#call-a-block-on-every-retry) for this as `will_retry_in` is one of the variables is gets passed. This is a block you can provide the middleware and is called after each failure, just before sleeping until the next retry:

```ruby
conn = Faraday.new(...) do |f|
  f.request :retry, retry_block: -> (env:, options:, retry_count:, exception:, will_retry_in:) do
    puts "Request failed, will try again in #{will_retry_in}s."
  end
  #...
end
```

Does this help you with what you were trying to do?
